# Generated by Django 5.0.2 on 2024-05-06 23:46

import django.core.validators
import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        ('student', '0003_alter_studentquestions_successes_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz123456789', length=15, max_length=30, prefix='exam-', primary_key=True, serialize=False, unique=True)),
                ('response_questions', models.TextField(default='')),
                ('time_taken', models.FloatField(default=0)),
                ('note', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('courses', models.ManyToManyField(to='app.course')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.module')),
                ('questions', models.ManyToManyField(to='app.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
