# Generated by Django 5.0.2 on 2024-05-07 01:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_alter_exam_date_alter_exam_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='date',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='time',
        ),
        migrations.AddField(
            model_name='exam',
            name='date_passed',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='time_passed',
            field=models.TimeField(auto_now=True),
        ),
    ]
