# Generated by Django 5.0.2 on 2024-05-15 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_course_correct_answers_and_more'),
        ('exam', '0005_exam_num_correct_answers_alter_exam_time_passed'),
        ('student', '0012_alter_student_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject_answers_for_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answers', models.IntegerField(blank=True)),
                ('wrong_answers', models.IntegerField(blank=True, default=0, null=True)),
                ('course', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
