# Generated by Django 5.0.2 on 2024-05-15 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_subject_answers_for_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject_answers_for_student',
            name='time_taking',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
