# Generated by Django 5.0.2 on 2024-05-15 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_subject_answers_for_student_time_taking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject_answers_for_student',
            name='correct_answers',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='subject_answers_for_student',
            name='time_taking',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
