# Generated by Django 5.0.2 on 2024-05-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_course_correct_answers_course_wrong_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='wrong_answers',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
