# Generated by Django 5.0.2 on 2024-04-15 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentquestions',
            old_name='failures_time',
            new_name='successes_time',
        ),
        migrations.RenameField(
            model_name='studentquestions',
            old_name='failures_time_index',
            new_name='successes_time_index',
        ),
    ]
