# Generated by Django 5.0.2 on 2024-04-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rename_failures_time_studentquestions_successes_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentquestions',
            name='successes_time',
            field=models.FloatField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
