# Generated by Django 5.0.2 on 2024-02-18 00:44

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_lesson_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward', models.FloatField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.questionexam')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=10, max_length=20, prefix='stud-', unique=True)),
                ('name', models.CharField(max_length=100)),
                ('questions', models.ManyToManyField(related_name='students', through='app.QuestionReward', to='app.questionexam')),
            ],
        ),
        migrations.AddField(
            model_name='questionreward',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student'),
        ),
    ]
