# Generated by Django 5.0.2 on 2024-05-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('student', '0003_alter_studentquestions_successes_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses_exams',
            field=models.ManyToManyField(null=True, to='app.course'),
        ),
    ]
