# Generated by Django 5.0.2 on 2024-05-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('student', '0004_student_courses_exams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='courses_exams',
            field=models.ManyToManyField(to='app.course'),
        ),
    ]
