# Generated by Django 5.0.2 on 2024-05-12 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('student', '0005_alter_student_courses_exams'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='module_exams',
            field=models.ManyToManyField(to='app.module'),
        ),
    ]
