# Generated by Django 5.0.2 on 2024-05-12 19:35

import student.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('student', '0006_student_module_exams'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='img',
            field=models.ImageField(blank=True, upload_to=student.models.upload_img),
        ),
        migrations.AlterField(
            model_name='student',
            name='courses_exams',
            field=models.ManyToManyField(blank=True, to='app.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='module_exams',
            field=models.ManyToManyField(blank=True, to='app.module'),
        ),
    ]
