# Generated by Django 5.0.2 on 2024-05-14 18:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_student_about_student_city_student_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birth_day',
            field=models.DateField(null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid date in the format "YYYY-MM-DD".', regex='^\\d{4}-\\d{2}-\\d{2}$')]),
        ),
    ]
