# Generated by Django 5.0.2 on 2024-05-14 19:08

import student.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_alter_student_address_alter_student_birth_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='img',
            field=models.ImageField(blank=True, default='static/static2/images/myImage/user.png', upload_to=student.models.upload_img),
        ),
    ]
