# Generated by Django 5.0.2 on 2024-05-15 00:33

import student.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_alter_student_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='img',
            field=models.ImageField(blank=True, default='images/students/user.png', upload_to=student.models.upload_img),
        ),
    ]
